#!/bin/bash
# ============================================================
# add-domain.sh — Add a new custom domain for a tenant app
# Usage: sudo bash add-domain.sh myshop.com admin@email.com
# ============================================================

DOMAIN=$1
EMAIL=$2
NEXTJS_PORT=3000

if [ -z "$DOMAIN" ] || [ -z "$EMAIL" ]; then
  echo "Usage: sudo bash add-domain.sh <domain> <admin-email>"
  echo "Example: sudo bash add-domain.sh myshop.com admin@myplatform.com"
  exit 1
fi

echo "➤ Adding domain: $DOMAIN"

# Create nginx config for this domain
NGINX_CONF="/etc/nginx/sites-available/$DOMAIN"

cat > "$NGINX_CONF" << EOF
# Auto-generated by add-domain.sh for $DOMAIN
# Generated: $(date)

server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN www.$DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    client_max_body_size 20M;

    location /_next/static/ {
        proxy_pass http://127.0.0.1:$NEXTJS_PORT;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        proxy_pass http://127.0.0.1:$NEXTJS_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF

echo "✓ nginx config written to $NGINX_CONF"

# Enable the site
ln -sf "$NGINX_CONF" "/etc/nginx/sites-enabled/$DOMAIN"

# Test nginx config
nginx -t
if [ $? -ne 0 ]; then
  echo "✗ nginx config test failed! Check the config above."
  exit 1
fi

# Reload nginx (temporary HTTP only, before SSL)
nginx -s reload
echo "✓ nginx reloaded (HTTP only)"

# Issue SSL certificate with Let's Encrypt
echo "➤ Issuing SSL certificate for $DOMAIN..."
certbot --nginx -d "$DOMAIN" -d "www.$DOMAIN" --non-interactive --agree-tos -m "$EMAIL"

if [ $? -eq 0 ]; then
  echo "✓ SSL certificate issued!"
  nginx -s reload
  echo "✓ Done! $DOMAIN is now live with HTTPS."
else
  echo "✗ SSL issuance failed. Make sure DNS A record points to this server."
  echo "  After fixing DNS, run: certbot --nginx -d $DOMAIN -d www.$DOMAIN -m $EMAIL"
fi
